const hardcodedQuestions = [
  "What is the Ultima 5 (U5)?",
  "What comes in my Ultima 5 kit?",
  "How do I set up the Ultima 5?",
  "What do CH1 and CH2 mean on my Ultima 5?",
  "Can I use only two electrode pads with my Ultima 5?",
  "How do I turn my Ultima 5 on and off?",
  "What settings should I use for my very first Ultima 5 session?",
  "What's different between the current Ultima 5 and the earlier model?",
  "Where can I learn more about my Ultima 5?",
  "How do I use a TENS unit, step by step?",
  "Can I use more than one channel at a time?",
  "Which mode should I use?",
  "How high should I turn up the intensity?",
  "Should the stimulation feel strong or gentle?",
  "What program should I use for my condition?",
  "How many minutes should I do per session?",
  "What wave forms does the Ultima 5 offer, and which one should I use?",
  "Why does the intensity reset to zero when I switch modes?",
  "Does my Ultima 5 remember my last settings when I turn it back on?",
  "What is the auto-repeat feature when adjusting pulse rate or pulse width?",
  "How do the intensity knobs work on my Ultima 5?",
  "What does the Compliance Monitor track, and why does it matter?",
  "What is the Lock/Unlock feature, and how do I use it?",
  "How do I change the waveform on my Ultima 5?",
  "How do I set the treatment timer on my Ultima 5?",
  "How should I approach electrode placement?",
  "Where should I place the pads for lower back pain?",
  "Where do I put the pads for neck pain?",
  "Can I place the pads directly over where the pain is?",
  "Can the pads touch each other?",
  "How far apart should the pads be?",
  "How far apart should the electrode pads be on my Ultima 5?",
  "How does a TENS unit work?",
  "What does a TENS unit actually do?",
  "What does a TENS unit feel like?",
  "What are the theories behind how TENS units work?",
  "Does TENS actually work?",
  "How long does it take to feel relief?",
  "Is pain relief immediate or temporary?",
  "Does TENS help reduce inflammation?",
  "What pain conditions does TENS help with?",
  "What frequency is best for chronic pain?",
  "What frequency works best for acute pain?",
  "Can I use a TENS unit every day?",
  "How often should I use a TENS unit?",
  "Can I use TENS more than once a day?",
  "Can I wear a TENS unit all day?",
  "Why does the sensation fade after a few minutes?",
  "Will my body get used to TENS?",
  "How do I maximize pain relief?",
  "What's the difference between TENS and EMS?",
  "Can one device do both TENS and EMS?",
  "Can TENS help me avoid pain medication?",
  "Can TENS speed up healing or does it only mask pain?",
  "Why don't I feel anything when I turn on my Ultima 5?",
  "Why is CH1 or CH2 flashing on my Ultima 5?",
  "How do I turn Pad Contact Detection on or off?",
  "Why can't I change the intensity on my Ultima 5?",
  "Why isn't my TENS unit producing sensation?",
  "Does the red light on the charger go out?",
  "How do you know when the batteries are charged?",
  "Why am I not feeling sensation?",
  "Why does the stimulation seem weak?",
  "Why is only one pad working?",
  "Why does the stimulation feel sharp instead of comfortable?",
  "Stimulation feels sharp or uncomfortable",
  "Why does the intensity suddenly decrease?",
  "Why does intensity drop during use?",
  "Why does my unit keep turning off?",
  "Why won't my TENS unit turn on?",
  "What are typical troubleshooting issues with TENS units?",
  "What does the Pad Contact Interruption Alarm do on my Ultima 5?",
  "How do I read the battery level indicator on my Ultima 5?",
  "Does my Ultima 5 automatically shut off if I forget to turn it off?",
  "What are Soft-Touch electrodes, and why do they matter?",
  "What's the difference between the Soft-Touch Silver and Clinical Grade electrode lines?",
  "How long do TENS pads last?",
  "When should I replace the pads?",
  "Why won't my pads stick anymore?",
  "How do I make my pads sticky again?",
  "Can I wash or clean electrode pads?",
  "Are generic pads compatible with my unit?",
  "What pads are compatible with my unit?",
  "What's the difference between 2 inch and 4 inch pads?",
  "How do I know which pads are best for me?",
  "What accessories should I buy with a TENS unit?",
  "What batteries can I use in the Ultima 5?",
  "How long does the battery last?",
  "Should I buy a rechargable batteries?",
  "Where should I never place TENS pads?",
  "Is it safe to use a TENS unit while sleeping?",
  "Can I drive while using a TENS unit?",
  "Can I use TENS with a pacemaker?",
  "Is a TENS unit safe to use during pregnancy?",
  "Can I use a TENS unit if I have diabetes?",
  "Can I use a TENS unit if I have metal implants?",
  "Is there contradictions with medication?",
  "Why does my skin turn red after treatment?",
  "I am experiencing skin irritation -- why is that?",
  "What should I do with the electrode pads after treatment?",
  "How do I clean and store the unit?",
  "What TENS unit is best for home use?",
  "Is a prescription required?",
  "What is interferential therapy?",
  "What is the difference between interferential therapy and TENS?",
  "How long are interferential therapy sessions typically?",
  "What is criss-cross pad application for interferential therapy?",
  "What is the IF4D?",
  "Can I use two or four electrodes with the IF4D?",
  "What treatment settings does the IF4D offer?",
  "What kind of waveform does the IF4D use?",
  "What comes with the IF4D?",
  "Can the IF4D run on batteries or wall power?",
];
