const hardcodedQuestions = [
  "How do I set up the Ultima 5?",
  "What do CH1 and CH2 mean on my Ultima 5?",
  "Can I use only two electrode pads with my Ultima 5?",
  "How do I change the waveform on my Ultima 5?",
  "How do I set the treatment timer on my Ultima 5?",
  "Why don't I feel anything when I turn on my Ultima 5?",
  "Why is CH1 or CH2 flashing on my Ultima 5?",
  "How do I turn Pad Contact Detection on or off?",
  "Why can't I change the intensity on my Ultima 5?",
  "Does the red light on the charger go out?",
  "How do you know when the batteries are charged?",
  "What batteries can I use in the Ultima 5?",
  "What should I do with the electrode pads after treatment?",
  "What is interferential therapy?",
  "What is the difference between interferential therapy and TENS?",
  "How long are interferential therapy sessions typically?",
  "What is criss-cross pad application for interferential therapy?",
  "What is the IF4D?",
  "Can I use two or four electrodes with the IF4D?",
  "What treatment settings does the IF4D offer?",
  "What kind of waveform does the IF4D use?",
  "What comes with the IF4D?",
  "Can the IF4D run on batteries or wall power?",
];
